# Generated by Django 3.1.5 on 2021-02-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R01 Орган',
                'verbose_name_plural': 'F1.0 R01 Органы',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R10',
                'verbose_name_plural': 'F1.0 R10',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R10_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R10.1',
                'verbose_name_plural': 'F1.0 R10.1',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R10_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R10.2',
                'verbose_name_plural': 'F1.0 R10.2',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R11',
                'verbose_name_plural': 'F1.0 R11',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R13 Квалификация',
                'verbose_name_plural': 'F1.0 R13 Квалификации',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R15 Тяжесть',
                'verbose_name_plural': 'F1.0 R15 Тяжести',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R16 Стадия совершения',
                'verbose_name_plural': 'F1.0 R16 Стадии совершения',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R17',
                'verbose_name_plural': 'F1.0 R17',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R18',
                'verbose_name_plural': 'F1.0 R18',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R19_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R19_1',
                'verbose_name_plural': 'F1.0 R19_1',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R19_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R19_2',
                'verbose_name_plural': 'F1.0 R19_2',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R19_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R19_3',
                'verbose_name_plural': 'F1.0 R19_3',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R1_ORGAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R01 Территориальный орган',
                'verbose_name_plural': 'F1.0 R01 Территориальные органы',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R02 Учесть',
                'verbose_name_plural': 'F1.0 R02 Учести',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R20',
                'verbose_name_plural': 'F1.0 R20',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R21',
                'verbose_name_plural': 'F1.0 R21',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R21_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R21.1',
                'verbose_name_plural': 'F1.0 R21.1',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R22 Отрасль',
                'verbose_name_plural': 'F1.0 R22 Отрасли',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R23',
                'verbose_name_plural': 'F1.0 R23',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R24',
                'verbose_name_plural': 'F1.0 R24',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R25 Код причиненного ущерба',
                'verbose_name_plural': 'F1.0 R25 Код причиненного ущерба',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R25_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R25.1 Код наркотических средств',
                'verbose_name_plural': 'F1.0 R25.1 Код наркотических средств',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R26 Способ совершения',
                'verbose_name_plural': 'F1.0 R26 Способы совершения',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R27 Дополнительная характеристика',
                'verbose_name_plural': 'F1.0 R27 Дополнительные характеристики',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R28 Совершено с приминением',
                'verbose_name_plural': 'F1.0 R28 Совершены с принимением',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R29',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R29 Характеристика охраны объекта',
                'verbose_name_plural': 'F1.0 R29 Характеристика охраны объекта',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R29_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R29.1 Результаты осмотра места происшествия',
                'verbose_name_plural': 'F1.0 R29.1 Результаты осмотра места происшествия',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R03 Вид',
                'verbose_name_plural': 'F1.0 R03 Виды',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R32 Личность потерпевшего не установена',
                'verbose_name_plural': 'F1.0 R32 Личность потерпевшего не установена',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R33',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R33 Характеристика потерпевших',
                'verbose_name_plural': 'F1.0 R33 Характеристика потерпевших',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R34',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R34 Социальное положение',
                'verbose_name_plural': 'F1.0 R34 Социальное положение',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R36 Гражданство',
                'verbose_name_plural': 'F1.0 R36 Гражданство',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R38 Цель приезда',
                'verbose_name_plural': 'F1.0 R38 Цель приезда',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R3_GASORG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R03 ГАС ОРГАН',
                'verbose_name_plural': 'F1.0 R03 ГАС ОРГАН',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R40 В производстве',
                'verbose_name_plural': 'F1.0 R40 В производстве',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R51',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R51 Административный участок',
                'verbose_name_plural': 'F1.0 R51 Административные участки',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R7_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R7.1 Восстановлено на учет в числе ППЛ',
                'verbose_name_plural': 'F1.0 R7.1 Восстановлены на учет в числе ППЛ',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R08 Преступление предотвращено',
                'verbose_name_plural': 'F1.0 R08 Преступления предотвращены',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R9 Преступление выявлено',
                'verbose_name_plural': 'F1.0 R9 Преступления выявлены',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R9_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R9.1',
                'verbose_name_plural': 'F1.0 R9.1',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R10 Характеристика группы',
                'verbose_name_plural': 'F1.1 R10 Характеристика группы',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R11 Характеристика связей группы',
                'verbose_name_plural': 'F1.1 R11 Характеристика связей группы',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R12 Характеристика лица',
                'verbose_name_plural': 'F1.1 R12 Характеристика лица',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R13 В состоянии опьянения',
                'verbose_name_plural': 'F1.1 R13 В состоянии опьянения',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R14 Ранее совершавшим',
                'verbose_name_plural': 'F1.1 R14 Ранее совершавшим',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R15 Ранее судимым',
                'verbose_name_plural': 'F1.1 R15 Ранее судимым',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R16 Рецидив преступления',
                'verbose_name_plural': 'F1.1 R16 Рецидив преступления',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R17 Преступление совершено обвиняемым',
                'verbose_name_plural': 'F1.1 R17 Преступление совершено обвиняемым',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R20 Место проживания',
                'verbose_name_plural': 'F1.1 R20 Место проживания',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R21 Цель приезда',
                'verbose_name_plural': 'F1.1 R21 Цель приезда',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R22 Национальность',
                'verbose_name_plural': 'F1.1 R22 Национальности',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R25 Решение по преступлению',
                'verbose_name_plural': 'F1.1 R25 Решения по преступлениям',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R26 Мотив',
                'verbose_name_plural': 'F1.1 R26 Мотивы',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R27 Преступление выявлено',
                'verbose_name_plural': 'F1.1 R27 Преступление выявлено',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R28 Код ущерба',
                'verbose_name_plural': 'F1.1 R28 Код ущерба',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R30 Технические средства снятия информации',
                'verbose_name_plural': 'F1.1 R30 Технические средства снятия информации',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R31',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R31 Примененние криминалистических средств и методов',
                'verbose_name_plural': 'F1.1 R31 Примененние криминалистических средств и методов',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R32 Использование АБД, ИПС',
                'verbose_name_plural': 'F1.1 R32 Использование АБД, ИПС',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R32_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R32.1 Использование аппаратно-программных средств',
                'verbose_name_plural': 'F1.1 R32.1 Использование аппаратно-программных средств',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R33',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R33 Уголовное дело расследовано',
                'verbose_name_plural': 'F1.1 R33 Уголовное дело расследовано',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R35_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R35_1 Сообщение',
                'verbose_name_plural': 'F1.1 R35_1 Сообщение',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R35_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R35_2 Сообщение',
                'verbose_name_plural': 'F1.1 R35_2 Сообщение',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R35_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R35_3 Сообщение',
                'verbose_name_plural': 'F1.1 R35_3 Сообщение',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R36 Применялся',
                'verbose_name_plural': 'F1.1 R36 Применялся',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R09 Преступление совершено неоднократно',
                'verbose_name_plural': 'F1.1 R09 Преступление совершено неоднократно',
            },
        ),
        migrations.CreateModel(
            name='SPR_F12R10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.2 R10 Лицу, совершившему преступление предъявлено обвинение',
                'verbose_name_plural': 'F1.2 R10 Лицу, совершившему преступление предъявлено обвинение',
            },
        ),
        migrations.CreateModel(
            name='SPR_F12R11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.2 R11 В отношении обвиняемого избраны меры пресечения',
                'verbose_name_plural': 'F1.2 R11 В отношении обвиняемого избраны меры пресечения',
            },
        ),
        migrations.CreateModel(
            name='SPR_F12R13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.2 R13 УД находится в производстве',
                'verbose_name_plural': 'F1.2 R13 УД находится в производстве',
            },
        ),
        migrations.CreateModel(
            name='SPR_F12R14_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.2 R14.1 Установлено отедалми УУР УМВД',
                'verbose_name_plural': 'F1.2 R14.1 Установлено отедалми УУР УМВД',
            },
        ),
        migrations.CreateModel(
            name='SPR_F12R9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.2 R9 Лицо задержано в порядке',
                'verbose_name_plural': 'F1.2 R9 Лицо задержано в порядке',
            },
        ),
        migrations.CreateModel(
            name='FORM1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r03_year', models.CharField(max_length=4, verbose_name='Год')),
                ('r03_gasps', models.CharField(max_length=17, verbose_name='Номер УД')),
                ('r04', models.CharField(max_length=2, verbose_name='Эпизод')),
                ('r11', models.DateField(verbose_name='Дата возбуждения УД')),
                ('r01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r1', verbose_name='Орган')),
                ('r01_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r1_organ', verbose_name='Код органа')),
                ('r02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r2', verbose_name='Учесть')),
                ('r03', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r3', verbose_name='Вид')),
                ('r03_gasorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r3_gasorg', verbose_name='Код терроргана ГАС')),
                ('r51', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r51', verbose_name='Административный участок')),
            ],
            options={
                'verbose_name': 'Статкарточка на выявленное преступление (ФОРМА 1)',
                'verbose_name_plural': 'Статкарточки на выявленное преступление (ФОРМА 1)',
            },
        ),
    ]
