# Generated by Django 3.1.5 on 2021-01-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0R02 Учесть',
                'verbose_name_plural': 'F1.0R02 Учести',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0R03 Вид',
                'verbose_name_plural': 'F1.0R03 Виды',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R3_GASORG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0R03 ГАС ОРГАН',
                'verbose_name_plural': 'F1.0R03 ГАС ОРГАН',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0R08 Преступление предотвращено',
                'verbose_name_plural': 'F1.0R08 Преступления предотвращены',
            },
        ),
        migrations.AlterField(
            model_name='spr_f10r1',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='spr_f10r1_organ',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Код'),
        ),
    ]
