# Generated by Django 3.1.5 on 2021-02-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spr_f10r1',
            options={'ordering': ['-code'], 'verbose_name': 'F1.0 R01 Орган', 'verbose_name_plural': 'F1.0 R01 Органы'},
        ),
    ]
