# Generated by Django 3.1.5 on 2021-02-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R10',
                'verbose_name_plural': 'F1.0 R10',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R10_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R10.1',
                'verbose_name_plural': 'F1.0 R10.1',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R10_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R10.2',
                'verbose_name_plural': 'F1.0 R10.2',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R11',
                'verbose_name_plural': 'F1.0 R11',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R13 Квалификация',
                'verbose_name_plural': 'F1.0 R13 Квалификации',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R7_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R7.1 Восстановлено на учет в числе ППЛ',
                'verbose_name_plural': 'F1.0 R7.1 Восстановлены на учет в числе ППЛ',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R9 Преступление выявлено',
                'verbose_name_plural': 'F1.0 R9 Преступления выявлены',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R9_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R9.1',
                'verbose_name_plural': 'F1.0 R9.1',
            },
        ),
    ]
