# Generated by Django 3.1.5 on 2021-01-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0002_auto_20210129_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R25 Решение по преступлению',
                'verbose_name_plural': 'F1.1 R25 Решения по преступлениям',
            },
        ),
        migrations.AlterModelOptions(
            name='spr_f10r1',
            options={'verbose_name': 'F1.0 R01 Орган', 'verbose_name_plural': 'F1.0 R01 Органы'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r1_organ',
            options={'verbose_name': 'F1.0 R01 Территориальный орган', 'verbose_name_plural': 'F1.0 R01 Территориальные органы'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r2',
            options={'verbose_name': 'F1.0 R02 Учесть', 'verbose_name_plural': 'F1.0 R02 Учести'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r3',
            options={'verbose_name': 'F1.0 R03 Вид', 'verbose_name_plural': 'F1.0 R03 Виды'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r3_gasorg',
            options={'verbose_name': 'F1.0 R03 ГАС ОРГАН', 'verbose_name_plural': 'F1.0 R03 ГАС ОРГАН'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r8',
            options={'verbose_name': 'F1.0 R08 Преступление предотвращено', 'verbose_name_plural': 'F1.0 R08 Преступления предотвращены'},
        ),
    ]
