# Generated by Django 3.1.5 on 2021-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0002_spr_f10r10_spr_f10r10_1_spr_f10r10_2_spr_f10r11_spr_f10r13_spr_f10r7_1_spr_f10r9_spr_f10r9_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R15 Тяжесть',
                'verbose_name_plural': 'F1.0 R15 Тяжести',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R16',
                'verbose_name_plural': 'F1.0 R16',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R17',
                'verbose_name_plural': 'F1.0 R17',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R18',
                'verbose_name_plural': 'F1.0 R18',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R19_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R19_1',
                'verbose_name_plural': 'F1.0 R19_1',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R19_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R19_2',
                'verbose_name_plural': 'F1.0 R19_2',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R19_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R19_3',
                'verbose_name_plural': 'F1.0 R19_3',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R20',
                'verbose_name_plural': 'F1.0 R20',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R21',
                'verbose_name_plural': 'F1.0 R21',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R21_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R21.1',
                'verbose_name_plural': 'F1.0 R21.1',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R22 Отрасль',
                'verbose_name_plural': 'F1.0 R22 Отрасли',
            },
        ),
    ]
