# Generated by Django 3.1.5 on 2021-02-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0003_auto_20210204_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spr_f10r10',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R10', 'verbose_name_plural': 'F1.0 R10'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r10_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R10.1', 'verbose_name_plural': 'F1.0 R10.1'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r10_2',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R10.2', 'verbose_name_plural': 'F1.0 R10.2'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r11',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R11', 'verbose_name_plural': 'F1.0 R11'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r13',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R13 Квалификация', 'verbose_name_plural': 'F1.0 R13 Квалификации'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r15',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R15 Тяжесть', 'verbose_name_plural': 'F1.0 R15 Тяжести'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r16',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R16 Стадия совершения', 'verbose_name_plural': 'F1.0 R16 Стадии совершения'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r17',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R17', 'verbose_name_plural': 'F1.0 R17'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r18',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R18', 'verbose_name_plural': 'F1.0 R18'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r19_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R19_1', 'verbose_name_plural': 'F1.0 R19_1'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r19_2',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R19_2', 'verbose_name_plural': 'F1.0 R19_2'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r19_3',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R19_3', 'verbose_name_plural': 'F1.0 R19_3'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r1_organ',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R01 Территориальный орган', 'verbose_name_plural': 'F1.0 R01 Территориальные органы'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r2',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R02 Учесть', 'verbose_name_plural': 'F1.0 R02 Учести'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r20',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R20', 'verbose_name_plural': 'F1.0 R20'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r21',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R21', 'verbose_name_plural': 'F1.0 R21'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r21_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R21.1', 'verbose_name_plural': 'F1.0 R21.1'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r22',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R22 Отрасль', 'verbose_name_plural': 'F1.0 R22 Отрасли'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r23',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R23', 'verbose_name_plural': 'F1.0 R23'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r24',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R24', 'verbose_name_plural': 'F1.0 R24'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r25_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R25.1 Код наркотических средств', 'verbose_name_plural': 'F1.0 R25.1 Код наркотических средств'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r26',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R26 Способ совершения', 'verbose_name_plural': 'F1.0 R26 Способы совершения'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r27',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R27 Дополнительная характеристика', 'verbose_name_plural': 'F1.0 R27 Дополнительные характеристики'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r28',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R28 Совершено с приминением', 'verbose_name_plural': 'F1.0 R28 Совершены с принимением'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r29',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R29 Характеристика охраны объекта', 'verbose_name_plural': 'F1.0 R29 Характеристика охраны объекта'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r29_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R29.1 Результаты осмотра места происшествия', 'verbose_name_plural': 'F1.0 R29.1 Результаты осмотра места происшествия'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r3',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R03 Вид', 'verbose_name_plural': 'F1.0 R03 Виды'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r32',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R32 Личность потерпевшего не установена', 'verbose_name_plural': 'F1.0 R32 Личность потерпевшего не установена'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r33',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R33 Характеристика потерпевших', 'verbose_name_plural': 'F1.0 R33 Характеристика потерпевших'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r34',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R34 Социальное положение', 'verbose_name_plural': 'F1.0 R34 Социальное положение'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r38',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R38 Цель приезда', 'verbose_name_plural': 'F1.0 R38 Цель приезда'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r3_gasorg',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R03 ГАС ОРГАН', 'verbose_name_plural': 'F1.0 R03 ГАС ОРГАН'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r40',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R40 В производстве', 'verbose_name_plural': 'F1.0 R40 В производстве'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r51',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R51 Административный участок', 'verbose_name_plural': 'F1.0 R51 Административные участки'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r7_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R7.1 Восстановлено на учет в числе ППЛ', 'verbose_name_plural': 'F1.0 R7.1 Восстановлены на учет в числе ППЛ'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r8',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R08 Преступление предотвращено', 'verbose_name_plural': 'F1.0 R08 Преступления предотвращены'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r9',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R9 Преступление выявлено', 'verbose_name_plural': 'F1.0 R9 Преступления выявлены'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r9_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.0 R9.1', 'verbose_name_plural': 'F1.0 R9.1'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r10',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R10 Характеристика группы', 'verbose_name_plural': 'F1.1 R10 Характеристика группы'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r11',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R11 Характеристика связей группы', 'verbose_name_plural': 'F1.1 R11 Характеристика связей группы'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r12',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R12 Характеристика лица', 'verbose_name_plural': 'F1.1 R12 Характеристика лица'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r13',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R13 В состоянии опьянения', 'verbose_name_plural': 'F1.1 R13 В состоянии опьянения'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r14',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R14 Ранее совершавшим', 'verbose_name_plural': 'F1.1 R14 Ранее совершавшим'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r15',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R15 Ранее судимым', 'verbose_name_plural': 'F1.1 R15 Ранее судимым'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r16',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R16 Рецидив преступления', 'verbose_name_plural': 'F1.1 R16 Рецидив преступления'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r17',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R17 Преступление совершено обвиняемым', 'verbose_name_plural': 'F1.1 R17 Преступление совершено обвиняемым'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r20',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R20 Место проживания', 'verbose_name_plural': 'F1.1 R20 Место проживания'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r21',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R21 Цель приезда', 'verbose_name_plural': 'F1.1 R21 Цель приезда'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r22',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R22 Национальность', 'verbose_name_plural': 'F1.1 R22 Национальности'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r25',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R25 Решение по преступлению', 'verbose_name_plural': 'F1.1 R25 Решения по преступлениям'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r26',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R26 Мотив', 'verbose_name_plural': 'F1.1 R26 Мотивы'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r27',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R27 Преступление выявлено', 'verbose_name_plural': 'F1.1 R27 Преступление выявлено'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r28',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R28 Код ущерба', 'verbose_name_plural': 'F1.1 R28 Код ущерба'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r30',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R30 Технические средства снятия информации', 'verbose_name_plural': 'F1.1 R30 Технические средства снятия информации'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r31',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R31 Примененние криминалистических средств и методов', 'verbose_name_plural': 'F1.1 R31 Примененние криминалистических средств и методов'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r32',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R32 Использование АБД, ИПС', 'verbose_name_plural': 'F1.1 R32 Использование АБД, ИПС'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r32_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R32.1 Использование аппаратно-программных средств', 'verbose_name_plural': 'F1.1 R32.1 Использование аппаратно-программных средств'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r33',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R33 Уголовное дело расследовано', 'verbose_name_plural': 'F1.1 R33 Уголовное дело расследовано'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r35_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R35_1 Сообщение', 'verbose_name_plural': 'F1.1 R35_1 Сообщение'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r35_2',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R35_2 Сообщение', 'verbose_name_plural': 'F1.1 R35_2 Сообщение'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r35_3',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R35_3 Сообщение', 'verbose_name_plural': 'F1.1 R35_3 Сообщение'},
        ),
        migrations.AlterModelOptions(
            name='spr_f11r36',
            options={'ordering': ['code'], 'verbose_name': 'F1.1 R36 Применялся', 'verbose_name_plural': 'F1.1 R36 Применялся'},
        ),
        migrations.AlterModelOptions(
            name='spr_f12r10',
            options={'ordering': ['code'], 'verbose_name': 'F1.2 R10 Лицу, совершившему преступление предъявлено обвинение', 'verbose_name_plural': 'F1.2 R10 Лицу, совершившему преступление предъявлено обвинение'},
        ),
        migrations.AlterModelOptions(
            name='spr_f12r11',
            options={'ordering': ['code'], 'verbose_name': 'F1.2 R11 В отношении обвиняемого избраны меры пресечения', 'verbose_name_plural': 'F1.2 R11 В отношении обвиняемого избраны меры пресечения'},
        ),
        migrations.AlterModelOptions(
            name='spr_f12r13',
            options={'ordering': ['code'], 'verbose_name': 'F1.2 R13 УД находится в производстве', 'verbose_name_plural': 'F1.2 R13 УД находится в производстве'},
        ),
        migrations.AlterModelOptions(
            name='spr_f12r14_1',
            options={'ordering': ['code'], 'verbose_name': 'F1.2 R14.1 Установлено отедалми УУР УМВД', 'verbose_name_plural': 'F1.2 R14.1 Установлено отедалми УУР УМВД'},
        ),
        migrations.AlterModelOptions(
            name='spr_f12r9',
            options={'ordering': ['code'], 'verbose_name': 'F1.2 R9 Лицо задержано в порядке', 'verbose_name_plural': 'F1.2 R9 Лицо задержано в порядке'},
        ),
    ]
