# Generated by Django 3.1.5 on 2021-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0003_spr_f10r15_spr_f10r16_spr_f10r17_spr_f10r18_spr_f10r19_1_spr_f10r19_2_spr_f10r19_3_spr_f10r20_spr_f1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R23',
                'verbose_name_plural': 'F1.0 R23',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R24',
                'verbose_name_plural': 'F1.0 R24',
            },
        ),
    ]
