# Generated by Django 3.1.5 on 2021-02-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0004_auto_20210204_0659'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='form1',
            index=models.Index(fields=['r01', 'r02', 'r03_year', 'r03_gasorg', 'r04'], name='inx_form1_gasps'),
        ),
    ]
