# Generated by Django 3.1.5 on 2021-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0004_spr_f10r23_spr_f10r24'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R25 Код причиненного ущерба',
                'verbose_name_plural': 'F1.0 R25 Код причиненного ущерба',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R25_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R25.1 Код наркотических средств',
                'verbose_name_plural': 'F1.0 R25.1 Код наркотических средств',
            },
        ),
    ]
