# Generated by Django 3.1.5 on 2021-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0005_spr_f10r25_spr_f10r25_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R26 Способ совершения',
                'verbose_name_plural': 'F1.0 R26 Способы совершения',
            },
        ),
    ]
