# Generated by Django 3.1.5 on 2021-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0005_auto_20210204_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F2R10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F2 R10 Пол',
                'verbose_name_plural': 'F2 R10 Пол',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SPR_F2R12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F2 R12 Образование',
                'verbose_name_plural': 'F2 R12 Образование',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SPR_F2R15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F2 R15 Место проживания',
                'verbose_name_plural': 'F2 R15 Место проживания',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SPR_F2R16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F2 R16 Цель приезда',
                'verbose_name_plural': 'F2 R16 Цель приезда',
                'ordering': ['code'],
            },
        ),
    ]
