# Generated by Django 3.1.5 on 2021-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0006_spr_f10r26'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_F10R27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R27 Дополнительная характеристика',
                'verbose_name_plural': 'F1.0 R27 Дополнительные характеристики',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R28 Совершено с приминением',
                'verbose_name_plural': 'F1.0 R28 Совершены с принимением',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R29',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R29 Характеристика охраны объекта',
                'verbose_name_plural': 'F1.0 R29 Характеристика охраны объекта',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R29_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R29.1 Результаты осмотра места происшествия',
                'verbose_name_plural': 'F1.0 R29.1 Результаты осмотра места происшествия',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R32 Личность потерпевшего не установена',
                'verbose_name_plural': 'F1.0 R32 Личность потерпевшего не установена',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R33',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R33 Характеристика потерпевших',
                'verbose_name_plural': 'F1.0 R33 Характеристика потерпевших',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R34',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R34 Социальное положение',
                'verbose_name_plural': 'F1.0 R34 Социальное положение',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R36 Гражданство',
                'verbose_name_plural': 'F1.0 R36 Гражданство',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R38 Цель приезда',
                'verbose_name_plural': 'F1.0 R38 Цель приезда',
            },
        ),
        migrations.CreateModel(
            name='SPR_F10R40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.0 R40 В производстве',
                'verbose_name_plural': 'F1.0 R40 В производстве',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R10 Характеристика группы',
                'verbose_name_plural': 'F1.1 R10 Характеристика группы',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R11 Характеристика связей группы',
                'verbose_name_plural': 'F1.1 R11 Характеристика связей группы',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R12 Характеристика лица',
                'verbose_name_plural': 'F1.1 R12 Характеристика лица',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R13 В состоянии опьянения',
                'verbose_name_plural': 'F1.1 R13 В состоянии опьянения',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R14 Ранее совершавшим',
                'verbose_name_plural': 'F1.1 R14 Ранее совершавшим',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R15 Ранее судимым',
                'verbose_name_plural': 'F1.1 R15 Ранее судимым',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R16 Рецидив преступления',
                'verbose_name_plural': 'F1.1 R16 Рецидив преступления',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R17 Преступление совершено обвиняемым',
                'verbose_name_plural': 'F1.1 R17 Преступление совершено обвиняемым',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R20 Место проживания',
                'verbose_name_plural': 'F1.1 R20 Место проживания',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R21 Цель приезда',
                'verbose_name_plural': 'F1.1 R21 Цель приезда',
            },
        ),
        migrations.CreateModel(
            name='SPR_F11R9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'F1.1 R09 Преступление совершено неоднократно',
                'verbose_name_plural': 'F1.1 R09 Преступление совершено неоднократно',
            },
        ),
    ]
