# Generated by Django 3.1.5 on 2021-02-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0009_spr_f10r51_spr_f11r31_spr_f11r32_spr_f11r32_1_spr_f11r33_spr_f11r35_1_spr_f11r35_2_spr_f11r35_3_spr_'),
    ]

    operations = [
        migrations.CreateModel(
            name='FORM1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r03_year', models.CharField(max_length=4, verbose_name='Год')),
                ('r01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r1', verbose_name='Орган')),
                ('r01_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r1_organ', verbose_name='Код органа')),
                ('r02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r2', verbose_name='Учесть')),
                ('r03', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r3', verbose_name='Вид')),
                ('r51', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statcards.spr_f10r51', verbose_name='Административный участок')),
            ],
        ),
    ]
