# Generated by Django 3.1.5 on 2021-02-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0010_form1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_f10r1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r10',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r10_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r10_2',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r11',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r13',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r15',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r16',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r17',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r18',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r19_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r19_2',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r19_3',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r1_organ',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r2',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r20',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r21',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r21_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r22',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r23',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r24',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r25',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r25_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r26',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r27',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r28',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r29',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r29_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r3',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r32',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r33',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r34',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r36',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r38',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r3_gasorg',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r40',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r51',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r7_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r8',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r9',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f10r9_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r10',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r11',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r12',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r13',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r14',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r15',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r16',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r17',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r20',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r21',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r22',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r25',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r26',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r27',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r28',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r30',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r31',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r32',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r32_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r33',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r35_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r35_2',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r35_3',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r36',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f11r9',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f12r10',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f12r11',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f12r13',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f12r14_1',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spr_f12r9',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
    ]
