# Generated by Django 3.1.5 on 2021-02-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statcards', '0011_auto_20210203_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form1',
            options={'verbose_name': 'Статистическая карточка на выявленное преступление (ФОРМА 1)', 'verbose_name_plural': 'Статистические карточки на выявленное преступление (ФОРМА 1)'},
        ),
        migrations.AlterModelOptions(
            name='spr_f10r16',
            options={'verbose_name': 'F1.0 R16 Стадия совершения', 'verbose_name_plural': 'F1.0 R16 Стадии совершения'},
        ),
    ]
